In [1]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv("finalcsv1.csv")
df

1  1.1  1.2  1.3  1.4  1.5   2  2.1    4  4.1  ...  1.82  1.83  1.84  \
0     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
1     6    6    7    7   48   70  68   74   69   81  ...    28    28    23   
2     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
3     1    1    1    1    1    2   1    2    3    4  ...     0     0     0   
4     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
...  ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   ...   ...   ...   
3656  2    2    2    2    2    2   2  109  105  110  ...    97   100   106   
3657  2    2    2    2    2   90  94   89   96   86  ...    65    80    94   
3658  9   12   13   26   74   80  95  108  108  105  ...    45    42    38   
3659  1    1    1    1    1    2   1    2    2    2  ...     0     0     0   
3660  2    2    2    2    2    2   2  105   92   90  ...    80    75    72   

      1.85  1.86  0.29  1.87  0.30  0.31  0.32  
0        0     0     0     0     0     0     0  
1       20    17     7     6     6     0     0  
2        0     0     0     0     0     0     0  
3        0     1     0     0     0     0     0  
4        0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
3656     3     2     2     1     1     2     1  
3657   117     2     2     2     2     2     1  
3658    32    11     9     8     8     6     1  
3659     0     0     0     0     0     0     1  
3660     2     1     1     1     1     1     1  

[3661 rows x 785 columns]

In [4]:
x=df.iloc[:,:-1]

In [5]:
x

1  1.1  1.2  1.3  1.4  1.5   2  2.1    4  4.1  ...  2.21  1.82  1.83  \
0     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
1     6    6    7    7   48   70  68   74   69   81  ...    35    28    28   
2     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
3     1    1    1    1    1    2   1    2    3    4  ...     2     0     0   
4     0    0    0    0    0    0   0    0    0    0  ...     0     0     0   
...  ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   ...   ...   ...   
3656  2    2    2    2    2    2   2  109  105  110  ...    94    97   100   
3657  2    2    2    2    2   90  94   89   96   86  ...    64    65    80   
3658  9   12   13   26   74   80  95  108  108  105  ...    47    45    42   
3659  1    1    1    1    1    2   1    2    2    2  ...     3     0     0   
3660  2    2    2    2    2    2   2  105   92   90  ...    86    80    75   

      1.84  1.85  1.86  0.29  1.87  0.30  0.31  
0        0     0     0     0     0     0     0  
1       23    20    17     7     6     6     0  
2        0     0     0     0     0     0     0  
3        0     0     1     0     0     0     0  
4        0     0     0     0     0     0     0  
...    ...   ...   ...   ...   ...   ...   ...  
3656   106     3     2     2     1     1     2  
3657    94   117     2     2     2     2     2  
3658    38    32    11     9     8     8     6  
3659     0     0     0     0     0     0     0  
3660    72     2     1     1     1     1     1  

[3661 rows x 784 columns]

In [6]:
r=np.linalg.matrix_rank(x)
r

784

In [7]:
def normalize_data(data):
    min_vals = np.min(data, axis=0)
    max_vals = np.max(data, axis=0)
    normalized_data = (data - min_vals) / (max_vals - min_vals)
    return normalized_data

In [8]:
x = normalize_data(x)
print(x)

             1       1.1       1.2       1.3       1.4       1.5         2  \
0     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
1     0.500000  0.461538  0.033981  0.037433  0.209607  0.301724  0.331707   
2     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
3     0.083333  0.076923  0.004854  0.005348  0.004367  0.008621  0.004878   
4     0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
...        ...       ...       ...       ...       ...       ...       ...   
3656  0.166667  0.153846  0.009709  0.010695  0.008734  0.008621  0.009756   
3657  0.166667  0.153846  0.009709  0.010695  0.008734  0.387931  0.458537   
3658  0.750000  0.923077  0.063107  0.139037  0.323144  0.344828  0.463415   
3659  0.083333  0.076923  0.004854  0.005348  0.004367  0.008621  0.004878   
3660  0.166667  0.153846  0.009709  0.010695  0.008734  0.008621  0.009756   

           2.1         4       4.1  ...      2.21      1.82    

In [9]:
y=df.iloc[:,-1]

In [10]:
y

0       0
1       0
2       0
3       0
4       0
       ..
3656    1
3657    1
3658    1
3659    1
3660    1
Name: 0.32, Length: 3661, dtype: int64

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=25)

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
logistic=LogisticRegression()

In [15]:
logistic.fit(x_train,y_train)

C:\Users\chait\OneDrive\Desktop\pyt\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [16]:
pred = logistic.predict(x_test)

In [17]:
score = logistic.score(x_test, y_test)
print(score)

0.9699863574351978


In [18]:
from sklearn.metrics import confusion_matrix

In [19]:
confusion_matrix(y_test, pred)

array([[354,   5],
       [ 17, 357]], dtype=int64)

In [20]:
from sklearn import tree

In [21]:
decision=tree.DecisionTreeClassifier(max_depth=2)

In [22]:
decision.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=2)

In [23]:
pred=decision.predict(x_test)

In [24]:
pred

array([1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,

In [25]:
score=decision.score(x_test,y_test)
score

0.9740791268758526

In [26]:
confusion_matrix(y_test, pred)

array([[359,   0],
       [ 19, 355]], dtype=int64)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
random=RandomForestClassifier(max_depth=2, random_state=0)

In [29]:
random.fit(x_train,y_train)

RandomForestClassifier(max_depth=2, random_state=0)

In [30]:
pred=random.predict(x_test)

In [31]:
score=random.score(x_test,y_test)

In [32]:
score

0.9140518417462483

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test, pred)

array([[313,  46],
       [ 17, 357]], dtype=int64)